### ISSUE TITLE
Write documentation for leanpub orb

### ISSUE THREAD

**Issue by zzamboni** [zzamboni/leanpub-orb#1]
At the moment  the only documentation which exists is the example at https://github.com/zzamboni/leanpub-orb/blob/master/src/examples/tag-based-publishing.yml. It would be nice to have more documentation in the README.

**Comment by Lumexralph** [comment]
@zzamboni I would love to work on this but I don't know how to proceed, would you be kind to help?

**Comment by Lumexralph** [comment]
@zzamboni I have some  ideas but I would like to know what you want the README to contain.
